### ISSUE TITLE
Investigate what it will take to Dockerize TAKServer properly

### ISSUE THREAD

**Issue by rambo** [pvarki/docker-atak-server#12]
The official distribution docker is a mess to put it lightly, the shell scripts are fragile, everything runs as root etcetc.

There are multiple Java processes so the "right" way probably would be to make a docker composition where each process is in their own container but they talk to each other, all the certificate and client mission package stuff should probably be wrapped into Python (or some other less quick-and-dirty than bash -language) to make them less fragile, same for the initialisation stuff (which in a composition should be it's own container the others depend on). Make things run with least privilege etc.

Then split all of these things into tasks (remember that task:l is 4h) with clear descriptions.

Admin user creation via REST API needs to be able to talk to the TAKServer and tell it to add and authorize the user, IDK if the best way is to run some sort of RPC on the container with the server process and have the REST API call that via the internal network.

**Comment by rambo** [comment]
ref RPC https://gitlab.com/advian-oss/python-datastreamserviceapp_template or https://gitlab.com/advian-oss/rust-datastreamserviceapp_template if we want to compile and then copy only minimal binary to the container where it runs.

**Comment by benjamsf** [comment]
Isn't this by much completed by now?

**Comment by rambo** [comment]
Done (initially with sidecar, in 5.0+ we can probably do this better since ignite host is no longer hardcoded to localhost)
