### ISSUE TITLE
Changes to the default configuration file

### ISSUE THREAD

**Issue by M1kk0H** [pvarki/docker-atak-server#16]
Following changes are needed to default configuration file TAK_defaults.pref

- All measurement configuration
  - have to be defined
- location send interval
  - have to be defined
- Toolbar configuration
  - Add and remove tools, have to be defined
- Tools Arrange, remove and add needed icons 
  - have to be defined 

--------
Correct values have to be tested for first two cases. 
- "alt_unit_pref" class="class java.lang.String">1<  -->  value should be 2 (meters (m))
- "speed_unit_pref" class="class java.lang.String">1< --> value should be (KM per Hour (kmph))
- "rng_meters_display_pref" class="class java.lang.String">2000< --> value should be 1000

**Comment by rambo** [comment]
These are done on takrmapi level where the user configurations are actually generated.
