### ISSUE TITLE
TAK-Sovelluksen käyttöönotto-ohje

### ISSUE THREAD

**Issue by nhaapa** [pvarki/docker-atak-server#22]
[ ] ATAK
[ ] iTAK
[ ] WinTAK

**Comment by nhaapa** [comment]
https://www.figma.com/proto/nTH4hmmmmFnQGCL5IHMZfP/Tilauspalvelu-workflow?node-id=3-662&scaling=scale-down&page-id=3%3A661&starting-point-node-id=140%3A107

**Comment by M1kk0H** [comment]
Eord ohjeet tehty pitää tarkista Online ohjeen tilan

**Comment by M1kk0H** [comment]
Kaikille tehty
