### ISSUE TITLE
TAK-server admin-tunnukset tilaajalle

### ISSUE THREAD

**Issue by nhaapa** [pvarki/docker-atak-server#25]
Tilaajalla tai käyttäjällä tarve päästä luomaan uusia User Grouppeja, jotka mahdollistavat datafiidien näkyvyyden rajoittamisen.

Päätettävä toteutetaanko näin vain toiinallisuutena TAK Admin loppukäyttäjän työkaluun. 

Kuinka saadaan
[ ] admin-tunnukset tilaajalle
[ ] admin-sivun url-tilaajalle

**Comment by M1kk0H** [comment]
Isue/ Käyttäjä stoori. https://github.com/pvarki/markdown-rasenmaeher-pm/issues/44

**Comment by M1kk0H** [comment]
Alkuperäistä tarvetta ei ole tarve toteuttaa, koska ATAK ja WinTAK sovelukset mahdollsitavat tämän. "Tilaajalla tai käyttäjällä tarve päästä serverille luomaan/muokkaamaan missin/groupeja. Liittyy DataSync-toimintoon."

Muokattu Issuen kuvausta ja pudotettu pois 1.0 julkaisusta.

**Comment by rambo** [comment]
Users marked as admin in RASENMAEHER have full admin privileges on the TAK-Server. Do note this race condition bug though https://github.com/pvarki/python-tak-rmapi/issues/50
