### ISSUE TITLE
WinTAK-asennuspaketin saaminen ladattavaksi tilauspalveluun

### ISSUE THREAD

**Issue by nhaapa** [pvarki/docker-atak-server#26]
[ ] jaettavan Zip-paketin luonti ilmanylimääräistä sälää

[ ]"WinTAK-nappi". WinTAK-asennuspalvelin & DataSync plugin ladattavaksi asennusta varten.

[ ] Samaa toiminnallisuutta voitaisiin käyttää tulevaisuudessa ladattavien .APK-pakettien kanssa.

[ ]  @benjamsf  selvitä onko lupa jakaa asennustiedosto [ Info Discord ]( https://discord.com/channels/1047112511603867668/1065931173441851423/1113723299311136889)

**Comment by M1kk0H** [comment]
tästä oma issue toteutuksesta Rasenmaherin puolella [ [KOPA Windows koneelle on tarve ladata WINTAK asennuspaketti](https://github.com/pvarki/markdown-rasenmaeher-pm/issues/47)#47 ](https://github.com/pvarki/markdown-rasenmaeher-pm/issues/47)

**Comment by M1kk0H** [comment]
Nyt olemassa linkki josta paketin saa ladattua. Tämä ok v.1,0.
