### ISSUE TITLE
Sync toiminnallisuus

### ISSUE THREAD

**Issue by nhaapa** [pvarki/docker-atak-server#31]
[ ] Pluginien toimivuus (Android, iOS, Windows)
  - Luo ja Testaa erillaiset käyttötapaukset eri versioiden välillä
  - [Testitapaukset](https://1drv.ms/x/s!AnKRLUyTGmIpgioJVRvy47FxTeNj?e=XvS8DT)
  - Tavoitteena saada ymmärrys miten erillaiset toimenpiteet näkyvät eri versioissa/ logi merkinnöissä--> Mahdollistaa toimintatavoista päättämisen ja ohjeistuksen luomisen
  - 
[ ] TAK Missiot toiminnallisuus ja tarvittavat vakio Missiot (Suunnittele)
  - Thtävä päätös onko yksi vai kaksi Misionia aluksi. Testaaminen ja suunnittelu aloitetaan yhdellä missionilla

**Linkatut issuet**

-  https://github.com/pvarki/docker-atak-server/issues/30

**Comment by M1kk0H** [comment]
Linked to: https://github.com/pvarki/docker-atak-server/issues/30

**Comment by M1kk0H** [comment]
TAK 1.0 versio suunniteltu, ohjeistettu ja toteutettu käytössä 11/23
