### ISSUE TITLE
WinTAK tietohuolto

### ISSUE THREAD

**Issue by nhaapa** [pvarki/docker-atak-server#49]
Ohje tietojen poistosta käytön jälkeen.

Pelkkä ohjelman poisto ei riitä, vaan tiedot pitää poistaa winTAK:n sisällä, koska muuten edellisten käyttöjen tiedot (mm. palvelin) jäävät WinTAK:iin.

- [x] Word
- [x] Online

**Comment by M1kk0H** [comment]
tämä ok
